version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  app:
    build: .
    ports:
      - 3060:3060
    depends_on:
      - mongodb
    restart: always
    environment:
      MONGO_URL: mongodb://mongodb:27017/my_database
      DB_DEV: mongodb://mongodb:27017/my_database
      PORT: 3060
      