# name: Test Driven Development

# on:
#   push:
#     branches: 
#       - develop
#       - main
#     paths-ignore:
#       - '**.md'
#   pull_request:
#     branches: [develop,main]
#     paths-ignore:
#       - '**.md'
# jobs:
#     build:
#       runs-on: ${{matrix.os}}
#       strategy:
#         matrix:
#           os: [ubuntu-latest, windows-latest, macos-latest]
#       concurrency: 
#         group: docker_image
#         cancel-in-progress: false
#       steps:
#         - uses: actions/checkout@v2
#         - name: Build Docker image
#           run: docker build -t tdd:latest .
#         - name: Push Docker image
#           run: docker push tdd:latest
            